---
- name: Install necessary packages
  run_once: true
  apt: name={{ item }} state=latest
  with_items:
    - build-essential 
    - devscripts
    - debhelper
    - cdbs 
    - autotools-dev
    - dh-buildinfo
    - libdb-dev
    - libwrap0-dev 
    - libpam0g-dev 
    - libcups2-dev 
    - libkrb5-dev 
    - libltdl3-dev
    - libgcrypt11-dev
    - libcrack2-dev 
    - libavahi-client-dev 
    - libldap2-dev 
    - libacl1-dev 
    - libevent-dev 
    - d-shlibs 
    - dh-systemd
    - avahi-daemon
    - git

- name: Remove old build directory
  file: path=/tmp/netatalk state=absent

- name: Get netatalk
  git: repo=https://github.com/adiknoth/netatalk-debian dest=/tmp/netatalk/build

- name: Build netatalk
  command: creates=/tmp/netatalk/netatalk*.deb chdir=/tmp/netatalk/build debuild -b -uc -us

- name: Install netatalk
  shell: chdir=/tmp/netatalk dpkg -i libatalk*.deb netatalk*.deb
  tags: install

- name: Clean Up
  file: path=/tmp/netatalk state=absent
  tags: cleanup

##### netatalk #####

- name: Enable netatalk
  service: name=netatalk enabled=yes
  tags: netatalk

- name: Do Configuration
  template: src=afp.conf dest=/etc/netatalk/afp.conf
  tags: netatalk

- name: restart netatalk
  service: name=netatalk.service state=restarted
  tags: netatalk

##### avahi #####
- name: Enable avahi-daemon
  service: name=avahi-daemon enabled=yes
  tags: avahi

- name: copy avahi config
  copy: src=afpd.service dest=/etc/avahi/services/afpd.service
  tags: avahi

- name: edit nssswitch
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: 'hosts:'
    line: "hosts:    files mdns4_minimal [NOTFOUND=return] dns mdns4 mdns"
  tags: avahi

- name: restart avahi
  service: name=avahi-daemon.service state=restarted
  tags: avahi

